# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12AAycL5e0sg22dNVvs85H_Q_yeZnhZqT
"""

import streamlit as st
import librosa
import numpy as np
import pandas as pd
import joblib
import tsfel
from streamlit_mic_recorder import mic_recorder
from pydub import AudioSegment
import soundfile as sf
import os

# === 1. Load model & scaler ===
model = joblib.load('model_randomforest_tsfel.pkl')
scaler = joblib.load('scaler_tsfel.pkl')

# === 2. Load konfigurasi TSFEL ===
cfg = tsfel.get_features_by_domain('statistical')

# === 3. UI Streamlit ===
st.title("🎙️ Voice Command Recognition - Buka/Tutup")
st.write("Ucapkan **'buka'** atau **'tutup'**, lalu lihat hasil prediksi di bawah ini.")

# === 4. Pilihan input ===
st.subheader("🎧 Pilih metode input suara:")
input_choice = st.radio("Pilih salah satu:", ["🎤 Rekam Langsung", "📂 Upload File"])

file_path = None

# === 5. Mode rekam suara ===
if input_choice == "🎤 Rekam Langsung":
    st.info("Tekan tombol di bawah untuk mulai rekam, lalu tekan lagi untuk berhenti.")
    audio_data = mic_recorder(
        start_prompt="Mulai Rekam 🎙️",
        stop_prompt="Berhenti ⏹️",
        just_once=False,
        use_container_width=True,
    )

    if audio_data:
        st.audio(audio_data["bytes"])
        with open("temp_audio.wav", "wb") as f:
            f.write(audio_data["bytes"])
        file_path = "temp_audio.wav"

# === 6. Mode upload file ===
elif input_choice == "📂 Upload File":
    uploaded_file = st.file_uploader("Unggah file suara (.wav / .mp3)", type=["wav", "mp3"])
    if uploaded_file:
        with open("temp_audio.wav", "wb") as f:
            f.write(uploaded_file.getbuffer())
        file_path = "temp_audio.wav"
        st.audio(uploaded_file)

# === 7. Jika ada file audio, lakukan prediksi ===
if file_path:
    try:
        # Load audio
        audio = AudioSegment.from_file(file_path)
        sr = audio.frame_rate
        samples = np.array(audio.get_array_of_samples(), dtype=np.float32)
        signal = samples / np.max(np.abs(samples))

        # ==== Tambahan: trimming dan deteksi hening ====
        signal, _ = librosa.effects.trim(signal)  # buang bagian hening di awal/akhir
        energy = np.sum(signal ** 2) / len(signal)

        if energy < 0.001:
            st.warning("🔇 Tidak terdeteksi suara signifikan, coba bicara lebih keras.")
            st.stop()

        # ==== Ekstraksi fitur TSFEL ====
        df_features = tsfel.time_series_features_extractor(cfg, signal, fs=sr, verbose=0)
        X_new = df_features.values

        # ==== Normalisasi ====
        X_new_scaled = scaler.transform(X_new)

        # ==== Prediksi ====
        prediction = model.predict(X_new_scaled)
        proba = model.predict_proba(X_new_scaled)[0]

        label = prediction[0]
        confidence = np.max(proba) * 100

        # ==== Hasil prediksi ====
        if confidence < 60:
            st.warning("🤔 Suara kurang jelas, coba ulangi pengucapan.")
        else:
            st.success(f"🎯 Prediksi: **{label.upper()}** (Confidence: {confidence:.2f}%)")

    except Exception as e:
        st.error(f"Gagal membaca file audio: {e}")

else:
    st.info("Silakan rekam atau unggah file suara terlebih dahulu untuk diprediksi.")
