# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12AAycL5e0sg22dNVvs85H_Q_yeZnhZqT
"""

import streamlit as st
import librosa
import numpy as np
import pandas as pd
import joblib
import tsfel

# === 1. Load model & scaler ===
model = joblib.load('model_randomforest_tsfel.pkl')
scaler = joblib.load('scaler_tsfel.pkl')

# === 2. Load konfigurasi TSFEL ===
cfg = tsfel.get_features_by_domain('statistical')

# === 3. UI Streamlit ===
st.title("🎙️ Voice Command Recognition - Buka/Tutup")
st.write("Ucapkan 'buka' atau 'tutup', lalu lihat hasil prediksi di bawah ini.")

# === 4. Upload file audio ===
uploaded_file = st.file_uploader("Unggah file suara (.wav / .mp3)", type=["wav", "mp3"])

if uploaded_file is not None:
    # Simpan file sementara
    with open("temp_audio.wav", "wb") as f:
        f.write(uploaded_file.getbuffer())

    # === 5. Load audio dan ekstrak fitur ===
    signal, sr = librosa.load("temp_audio.wav", sr=None)
    df_features = tsfel.time_series_features_extractor(cfg, signal, fs=sr)

    # Pastikan hanya fitur statistik (drop label, dll)
    X_new = df_features.values

    # Normalisasi sesuai scaler training
    X_new_scaled = scaler.transform(X_new)

    # === 6. Prediksi ===
    prediction = model.predict(X_new_scaled)
    proba = model.predict_proba(X_new_scaled)[0]

    label = prediction[0]
    confidence = np.max(proba) * 100

    # === 7. Tampilkan hasil ===
    st.success(f"🎯 Prediksi: **{label.upper()}** (Confidence: {confidence:.2f}%)")

    # === 8. (Opsional) Visualisasi bentuk gelombang ===
    st.audio(uploaded_file)
    st.line_chart(signal)
else:
    st.info("Silakan unggah file suara terlebih dahulu untuk diprediksi.")
